// Copyright 2024 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics -i ae86.gif -f pal256`

#pragma once

#include <qp.h>

extern const uint32_t gfx_ae86_length;
extern const uint8_t  gfx_ae86[891929];
