#pragma once

#define SPI_DRIVER SPID0
#define SPI_MOSI_PIN GP7
#define SPI_SCK_PIN GP6

#define WS2812_PIO_USE_PIO1
#define WS2812_DI_PIN GP23
#define LED_CAPS_LOCK_PIN GP23
// #define RGBLED_NUM 1
#define RGBLIGHT_LED_COUNT 1

#define QUANTUM_PAINTER_DISPLAY_TIMEOUT 0
#define QUANTUM_PAINTER_SUPPORTS_256_PALETTE TRUE
// #define QUANTUM_PAINTER_SUPPORTS_NATIVE_COLORS TRUE
#define QUANTUM_PAINTER_NUM_IMAGES 2
#define QUANTUM_PAINTER_NUM_FONTS 1
#define QUANTUM_PAINTER_PIXDATA_BUFFER_SIZE 32
// #define QUANTUM_PAINTER_TASK_THROTTLE 500
// #define QUANTUM_PAINTER_DEBUG TRUE

// #define ENCODERS_PAD_A { GP20 }
// #define ENCODERS_PAD_B { GP19 }
#define ENCODERS_PAD_A { GP22 }
#define ENCODERS_PAD_B { GP21 }
#define ENCODER_RESOLUTION 4
// #define ENCODER_DEFAULT_POS 0x3
#define VIAL_KEYBOARD_UID {0x2D, 0x02, 0x7B, 0x51, 0xC0, 0x8E, 0x74, 0xFD}

#define MATRIX_ROWS 5
#define MATRIX_COLS 4